### ISSUE TITLE
Not detecting diyHue Hub

### ISSUE THREAD

**Issue by michaeldeborst** [sinedied/dmx-hue#14]
I've tried to link this to my virtualized diyHue Hue Hub but it does not detect the virtualized bridge. Here's my console log. In between setup commands I pushed the virtual link button, but it's still not detected.
```
sh-3.2# dmx-hue setup
No bridge found
sh-3.2# dmx-hue setup
No bridge found
sh-3.2# 
```

I'm running dmx-hue on my mac and the installation went without a hitch.
Do you have any tips? 
**Is it possible to specify a host ip address for dmx-hue setup. Maybe I can specify the ip address of my diyHue instance.**

**Comment by sinedied** [comment]
I don't know diyHue and never tried it, so I can't answer for sure if it's compatible.
This is the Hue library used to communicate with the bridge: https://github.com/peter-murray/node-hue-api
Make sure that your mac is on the same network as your Hue bridge to get it detected.
You can also use the `--ip` option to for the ip address of your diyHue instance and see if it works.

**Comment by michaeldeborst** [comment]
@sinedied How can I specify the --ip tag during setup?

**Comment by sinedied** [comment]
Add it to the when running the command: `hue setup --ip <adress>`
