### ISSUE TITLE
Not an issue but a silly question

### ISSUE THREAD

**Issue by raddwatson** [sinedied/dmx-hue#15]
Hey fairly new to this, planning a project.
From what I understand once this is installed I don't need to leave a pc/mac open to run this right?

As in after initial setup? or does there need to be a dedicated machine running this code you've developed constantly?

If not would it be feasible to have this running on a pi?

**Comment by sinedied** [comment]
You need to leave the program running to bridge the calls between ArtNet DMX and Hue API, it's not a one time configuration.
And yes it can run on a PI, it's fairly lightweight 😃
