### ISSUE TITLE
No bridge found

### ISSUE THREAD

**Issue by Shane54NZ** [sinedied/dmx-hue#2]
I keep getting "No bridge found", regardless of whether I run "dmx-hue setup" or "dmx-hue setup -i192.168.2.100".

I am positive that my bridge's IP is 192.168.2.100: when I point my browser at that IP, it loads the bridge's http page.

Is it possible that this only works with the gen2 bridge? I still have the gen1, the round one.

**Comment by sinedied** [comment]
I'm not sure, I used the `node-hue` API successfully when I had the v1 bridge before, so it should not be the version. Can you see your bridge with `dmx-hue setup -l`?

Also, did you try with a space before the IP: `dmx-hue setup -i 192.168.2.100`?

**Comment by Shane54NZ** [comment]
Super weird - I can ping the bridge and everything, but I keep getting "No bridge found" when I run dmx-hue setup:

![2017-09-13_1035](https://user-images.githubusercontent.com/13235917/30351392-3d925a44-986f-11e7-9e84-f821a231e5da.png)

Time to restart everything and try again ;-)

**Comment by Shane54NZ** [comment]
Still happening :-(

Is there anything I could do to diagnose what the issue could be? I would really like to get this working.

Thank you kindly in advance.

**Comment by sinedied** [comment]
If you're not currently connected to the same sub-network as your Hue bridge, the UPNP packets used for bridge discovery cannot be received, even though the bridge itself is reachable through ping.

I made a change to allow forcing the bridge IP manually even if it's not detected with UPNP, can you try the `1.3.2` version and tell me if it solves your issue?

**Comment by Shane54NZ** [comment]
And there it is. All works now (other than that Freestyler DMX has a bit of a learning curve, heh) and I'm super grateful that you took the time to give me a hand. Thanks so much! :-)

**Comment by sinedied** [comment]
Nice to know that it fixed your issue 😉
