### ISSUE TITLE
|| does not work if first value is 0 and second is 1.

### ISSUE THREAD

**Issue by RobertjanTuit** [sinedied/dmx-hue#26]
https://github.com/sinedied/dmx-hue/blob/6aa6a574f4d77dcf89ede24d7f4c008d8561f8b6/index.js#L273

Need something like to have it not always fall to second value:
      universe: this._args.universe === 0 ? 0 : (this._args.universe || Util.config.get('universe') || 0),

(I had config universe to 1 and was unable to argh override it to 0)

**Comment by sinedied** [comment]
Yes, that's an issue.
Can you open a PR for this?

**Comment by sinedied** [comment]
Fixed in 2.0
