### ISSUE TITLE
Are you able to select which lights on the bridge you want to control with this?

### ISSUE THREAD

**Issue by danyal** [sinedied/dmx-hue#27]
Maybe this is part of the setup process but are you able to select certain lights on the bridge and leave others out?

**Comment by sinedied** [comment]
You can change the light order in the config: https://github.com/sinedied/dmx-hue#setting-lights-order but I don't think you can currently disable lights to be mapped automatically.

**Comment by gemgemma** [comment]
Have you found a current work around on the automatic mapping?

**Comment by rjmunro** [comment]
You can select which lights to include as part of the setup process. 

I don't understand @sinedied 's comment. According to git blame it's been a feature since the initial commit 6 years ago:
https://github.com/sinedied/dmx-hue/blame/e1dd3ab9629f86cee68947b4cf18dee6341d1102/index.js#L207-L214

**Comment by sinedied** [comment]
@rjmunro You're right, it's been a while since I worked on this so my memory was failing 😅 

If you run `dmx-hue setup` you can select which light are enabled.
