### ISSUE TITLE
No bridge found

### ISSUE THREAD

**Issue by D0Msn** [sinedied/dmx-hue#29]
Hey actually tested it on Windows and on Raspberry.
And I'm not able to find the device by typing "dmx-hue setup" :(

Did the setup in the Hue App
Added 1 Lamp
Then in cmd: "dmx-hue setup"
Pressed the Button on the Bridge
again "dmx-hue setup"

But I'm not able to find any Bridge

Hue Essentials says:
Modell ID BSB002
API-Version 1.50.0
Softwareversion 1950207110

Is there anything wrong?
Thank you :)

**Comment by EmnichtdaYT** [comment]
Same problem here

**Comment by EmnichtdaYT** [comment]
Okay update, I was able to manually enter the bridge ip with the -i argument. @D0Msn you can try this too

**Comment by jordangriffey** [comment]
@EmnichtdaYT I'm having the same issue with the bridge but am pretty new to Command Prompt. Can you explain the -i argument a little more and let me know the full command you entered?

**Comment by ghost** [comment]
Ich habe mich mit dem Appel-Login angemeldet. Richtig wäre Facebook-Anmeldung gewesen.Ich kann das nicht mehr ändern, auch Deinstallieren und neu Installieren hat nicht geholfen.Niederurner Pub Andy BergerHauptstrasse 338867 Niederurnen0796721523 www.nidipub.chAm 19.09.2022 um 14:56 schrieb jordangriffey ***@***.******@***.*** I'm having the same issue with the bridge but am pretty new to Command Prompt. Can you explain the -i argument a little more and let me know the full command you entered?

**Comment by EmnichtdaYT** [comment]
> @EmnichtdaYT I'm having the same issue with the bridge but am pretty new to Command Prompt. Can you explain the -i argument a little more and let me know the full command you entered?

Oof. It's been quite a while now but I think the command was something like `dmx-hue setup -i [ip]` replacing [ip] with the ip address of your hue bridge.

Edit: It is recommended to change your bridges ip address to static so the address stays the same

**Comment by sinedied** [comment]
The new 2.0 version has been updated with the latest node-hue-api, it includes a new and more robust bridge detection mechanism that should fix this issue, so I'm closing this. 
If you encounter this bug again, please let me know
