### ISSUE TITLE
Instant No Bridge Found after typing dmx-hue setup

### ISSUE THREAD

**Issue by zynwire** [sinedied/dmx-hue#39]
I pressed the button and that but doesn't work, maybe I'm doing it wrong. Yes, i am on the Same Network

**Comment by sinedied** [comment]
What version are you using? (Run `dmx-hue --version`)

If it doesn't detect your bridge, you may try manually forcing its ip with `dmx-hue setup --ip <your_bridge_ip>`

**Comment by zynwire** [comment]
2.0.0
but i am going to just manually use ip then ty :)

**Comment by zynwire** [comment]
Still no Bridge Found

**Comment by zynwire** [comment]
And do you know any Nanoleaf Compatible Ones and by No Bridge Found i mean with manual IP

**Comment by zynwire** [comment]
Bro you going to Respond?

**Comment by zynwire** [comment]
bruh

**Comment by zynwire** [comment]
> What version are you using? (Run `dmx-hue --version`)
> 
> If it doesn't detect your bridge, you may try manually forcing its ip with `dmx-hue setup --ip <your_bridge_ip>`

respond bro
