### ISSUE TITLE
Transition/white channels not appearing, cannot re-order lights after changes to config file

### ISSUE THREAD

**Issue by toxic-teddy** [sinedied/dmx-hue#41]
![Screenshot 2023-07-15 at 12 53 20 PM](https://github.com/sinedied/dmx-hue/assets/118304260/6472a2bc-7e39-4b08-af87-2451bf8b5cef)

Hi, sinedied.
Any changes I make to the config file (even if I make those changes during setup) are not reflecting when I run dmx-hue.

I have tried:
1. Re-ordering my lights
2. Setting the transition time channel to yes
3. Enabling the white channels.

All I get are the default RGB channels for each of my Hue lights.
Unable to add the transition channel (channel 1, and re-order the lights is making it incompatible with the mapping I'd previously done in my DMX program, where I could see the transition channel and the lights in the proper order [1,3,2].

Is there a way to force the configuration? I've already tried deleting the config file and doing the setup again. No matter what, I only get the default light order with no transition time/white control channels.

**Comment by sinedied** [comment]
Looking into this, it may be because of the recent changes but there's no trace of this being used in the code anymore 😅 
Should be a quick fix

**Comment by sinedied** [comment]
Oups, the code was there but due to a silly regression config options were always ignored.
