### ISSUE TITLE
Unable to complete setup - No bridge found

### ISSUE THREAD

**Issue by filipers** [sinedied/dmx-hue#46]
Hello there, trying to setup my bridge but it doesn't work. 

When I type dmx-hue setup for the first time in one of my Windows 11 VMs, it finds my two bridges, I select one of them, then click on the link button on top of the bridge and proceed to run dmx-hue setup again but this time it doesn't find any bridges. If I run dmx-hue it says to run the setup again. What could be affecting the setup? I also tried on a MacOS laptop with the same results.

Thanks!

Outputs:

PS C:\Users\filip_y80qtot> dmx-hue setup
Found 2 bridge(s)
? Multiple bridges found, select the one to use Bridge02 (10.254.0.19)
No bridges found
PS C:\Users\filip_y80qtot> dmx-hue setup
No bridge found
PS C:\Users\filip_y80qtot> dmx-hue
0
Bridge not configured, run "dmx-hue setup"

**Comment by sinedied** [comment]
I never tried using VMs, so I'm not sure if that may cause issues.
You can try using the `dmx-hue setup --force` to override the existing configuration, and directly use `--ip` to set the IP address of a specific bridge.

**Comment by filipers** [comment]
@sinedied , thanks.
I actually tried a Windows 10 and it worked on first try. Not sure what else changed besides the OS. Thanks for the help!
