### ISSUE TITLE
Wont work with Daslight

### ISSUE THREAD

**Issue by jpbruneel** [sinedied/dmx-hue#5]
What am I doing wrong?
The setupinstructies works, see my bridge.
Program starts and see al the lights.
Start Daslight 4, patch in universe 1 faders, nothing happens!

Back to the frist question, whhat am I doping wrong?

Regards
JP

**Comment by sinedied** [comment]
Do you have a daslight usb controller with artnet support connected? Without it it seems to see other artnet nodes but won't emit any data :/

**Comment by jpbruneel** [comment]
Hi,
 yes I have connected a controller with artiste support.
When I first start up Daslight, then dmx-hue I get this error:
Error: bind EADDRINUSE 0.0.0.0:6454

Kind regards
JP

**Comment by sinedied** [comment]
You should have started by that :)
When running on the same machine, you have to start dmx-hue before Daslight (or any light control software) as they both creates an ArtNet node on the same port.
