### ISSUE TITLE
Error: No Bridge Found

### ISSUE THREAD

**Issue by Zeroaim-exe** [sinedied/dmx-hue#52]
unfortnuately i get the error message that no bridge was found. i also tried setting the IP manually. 
When connecting to the IP via my browser i see the web page so everything should work. The Hue-Sync Windows App works as well.

![image](https://github.com/sinedied/dmx-hue/assets/74614690/59217bb7-5e51-4947-9fc8-09ce4a85bdad)
![image](https://github.com/sinedied/dmx-hue/assets/74614690/5bd32d71-604a-4252-b195-de8a4390742a)

**Comment by Zeroaim-exe** [comment]
here is the semi-fixed code, it works but really messy and reqires to set the bridge ip manually in the code. idk maybe some1 has the time to finish it, i unfortunately dont:

import Color from 'color';
import { v3 as hue } from 'node-hue-api';
import inquirer from 'inquirer';
import Util from './util.js';

const { LightState } = hue.lightStates;
const APP_DESCRIPTION = 'dmx-hue utility';

class Hue {
  async getLights() {
    try {
      const api = await this.api();
      console.log('API instance created successfully.');

      const lights = await api.lights.getAll();
      console.log('API Response:', lights); 

      if (!lights || lights.length === 0) {
        console.log('No lights returned from API.');
        Util.exit('No lights found');
      }

      console.log('Lights found:', lights.map(light => light.name));
      return lights;
    } catch (error) {
      console.error('Failed to get lights:', error.message);
      console.error('Error details:', error); 
      Util.exit('No lights found');
    }
  }  


  createLightState(r, g, b, temperature, brightness, options) {
    const state = new LightState().transition(options.transition);
    const mapRange = (value, low1, high1, low2, high2) =>
      low2 + ((high2 - low2) * (value - low1)) / (high1 - low1);

    const mappedTemperature = options.white
      ? mapRange(temperature, 0, 255, 153, 500)
      : 0;
    const mappedBrightness = options.white
      ? mapRange(brightness, 0, 255, 0, 100)
      : 0;

    if (r === g && g === b && b === 0 && (!options.white || mappedBrightness === 0)) {
      state.off();
    } else if (r === g && g === b && b === 0 && options.white) {
      state.on().white(mappedTemperature, mappedBrightness);
    } else if (options.colorloop && r === g && g === b && b === 1) {
      state.on().effect('colorloop').sat(254).bri(254);
    } else {
      const hsv = Color.rgb(r, g, b).hsv().array();
      state.on().effect('none').hsb(hsv[0], hsv[1], hsv[2]);
    }
    return state;
  }

  async setLight(id, state) {
    try {
      const api = await this.api();
      await api.lights.setLightState(id, state);
      console.log(`Light state set for ${id}`);
    } catch (error) {
      console.error(`Unexpected error while setting light state: ${error.message}`);
    }
  }

  async listBridges(print) {
    try {
      console.log('Searching for Hue bridges...');
      let bridges = await hue.discovery.nupnpSearch();
      console.log('nUPnP Search results:', bridges);
      if (bridges.length === 0) {
        console.log('No bridges found with nUPnP, trying UPnP...');
        bridges = await hue.discovery.upnpSearch();
        console.log('UPnP Search results:', bridges);
      }

      if (bridges.length === 0) {
        console.log('No bridges found after all searches');
      } else {
        console.log(`Found ${bridges.length} bridge(s)`);
        if (print) {
          bridges.forEach(b => console.log(`- ${b.ipaddress} (${b.name})`));
        }
      }

      return bridges;
    } catch (error) {
      console.error('Error searching for bridges:', error);
      Util.exit('No bridge found');
    }
  }

  async setupBridge(ip = null, force = false) {
    try {
      if (ip) {
        console.log(`Using provided IP address: ${ip}`);
        this._api = await hue.api.createLocal(ip).connect();
        try {
          const user = await this._api.users.createUser(APP_DESCRIPTION);
          Util.config.set('user', user.username);  
          Util.config.set('bridge', ip);
          console.log('Bridge linked successfully with user:', user);
        } catch (error) {
          console.error('Error creating user:', error.message);
          Util.exit('Failed to create user on the bridge');
        }
      } else {
        const bridges = await this.listBridges(false);
        if (!bridges.length) throw new Error('No bridges found');
        const bridge = await inquirer.prompt([
          {
            type: 'list',
            name: 'bridge',
            message: 'Multiple bridges found, select the one to use',
            choices: bridges.map(b => ({ name: `${b.name} (${b.ipaddress})`, value: b }))
          }
        ]).then(result => result.bridge);
        this._api = await hue.api.createLocal(bridge.ipaddress).connect();
        const user = await this._api.users.createUser(APP_DESCRIPTION);
        Util.config.set('user', user.username);  
        Util.config.set('bridge', bridge.ipaddress);
        console.log('Bridge linked successfully with user:', user);
      }
    } catch (error) {
      console.error('Error during bridge setup:', error.message);
      Util.exit('Failed to setup the bridge');
    }
  }
  
  async api() {
    if (!this._api) {
      const bridge = Util.config.get('bridge');
      const username = Util.config.get('user');  
      console.log('Retrieved username:', username);  
      if (!bridge || !username) {
        console.error('Bridge or user not configured correctly:', { bridge, username });
        throw new Error('Bridge or user not configured');
      }
      console.log('Connecting to bridge at:', bridge, 'with user:', username);
      this._api = await hue.api.createLocal(bridge).connect(username);
    }
    return this._api;
  }

}

async function main() {
  const hueInstance = new Hue();
  await hueInstance.setupBridge('your.ip', true); // directly set the bridge IP
  await hueInstance.getLights();
}

main().catch(console.error);


export default Hue;

**Comment by Schreilix** [comment]
how did u fix it?
