### ISSUE TITLE
Error: bind EADDRINUSE 0.0.0.0:6454

### ISSUE THREAD

**Issue by brunorsini** [sinedied/dmx-hue#6]
Hi!

Ran setup but when I run dmx-hue on High Sierra I get the error mentioned on the topic... Really want to use my Hue lights with Resolume Arena, any ideas on what could be causing this?

Thanks a bunch :)

**Comment by sinedied** [comment]
When running on the same machine as your light software, you have to start dmx-hue before your light control software as they both creates an ArtNet node on the same port. Or you can use another device for running dmx-hue, like a raspberry PI.
