### ISSUE TITLE
Only one bulb can transition

### ISSUE THREAD

**Issue by Simon-Ince** [sinedied/dmx-hue#7]
Hi, I've got dmx-hue up and running and I've created a sequence in Vezer, if I manually scrub through and click on parts of the sequence the bulbs change to how they are set, but if I click play only the first bulb runs through the sequence and then when it hits the end all the other bulbs change.

Does anyone know what could be causing this?

**Comment by sinedied** [comment]
Are you sure you are not hitting the rate limit of the Hue API (it supports max. 10 bulb color changes / second, see https://github.com/sinedied/dmx-hue#philips-hue-response-times-vs-dmx) ?

By default, a (very naive) safe rate limiting is enforced on dmx-hue, but if you are sure you will not overflow your bridge with too much calls per second, you can try adding the `--no-limit` flag when running dmx-hue.
