### ISSUE TITLE
No node found: using QLC console to send to dmx-hue

### ISSUE THREAD

**Issue by wwwerk** [sinedied/dmx-hue#9]
Running dmx-hue on a system with eth0 and eth1 and Hue hub attached on local network.
Setup hue binding to eth1 using universe 1

QLC does not detect any "HueDMX" node on the network when configuring Outputs. 

Since the documentation indicates and recommends QLC, I wonder if there is further documentation for running both dmx-hue and QLC on the same system with multiple network interfaces.

**Comment by sinedied** [comment]
You have to start dmx-hue before start the QLC+ app, otherwise QLC+ will use the port to setup its own node server that will conflict with dmx-hue.

Once dmx-hue is started, you can start QLC+ and the node should appear in the list directly.

**Comment by wwwerk** [comment]
Thank you for the response but DMX-hue was started first. If it's started 2nd it returns an error and wont bind to eth0. 

I've also tried it on eth1 on the same subnet. 

I'm going to test it on a 2nd system in the same subnet.

I'll also check which ports it binds to and report back.

**Comment by sinedied** [comment]
Did you manage to get it working? I only tested in on my mac laptop which have also 2 networks interfaces, binding to default '0.0.0.0' address (which results to default active network interface I think), and QLC never had issue detecting it so I'm not sure what may be wrong here, especially as artnet protocol is very basic (use UDP broadcast).
